name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: linux
    permissions:
      contents: write
    steps:
      - uses: kadirlofca/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/New_York
          retries: 3
          retries_delay: 300
          config_display: large
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_colors: rainbow
          plugin_languages_limit: 4
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: ${{ secrets.STEAM_UID }}
          plugin_steam_sections: player, recently-played
